version: '3.6'

services:
    jupyter:
      volumes:
        - ./jupyter:/home/jovyan/work
      ports:
        - 8888:8888
      container_name: jupyter
      build: ./jupyter
      environment:
        - JUPYTER_ENABLE_LAB=yes
      command: "start-notebook.sh"